name: Live demo

on:
  push:
    branches: [master]

permissions:
  contents: read

concurrency:
  group: live-demo-master
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Start browser container
        run: |
          docker pull yinfra/html-reporter-browsers
          docker run -d --name demo-browsers --rm --network=host yinfra/html-reporter-browsers
      - name: Generate demo
        env:
          SERVER_HOST: localhost
        run: npm run --workspace=demo generate
      - name: Publish demo
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ru-central1
        run: node scripts/demo/publish.js --report test/func/fixtures/demo/report
