name: NPM publish

on:
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: Version Type
        required: true
        options:
        - patch
        - minor
        - major
jobs:
    name: Publishing to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node JS
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run build
      - run: npm run release -- --release-as ${{ github.event.inputs.versionType }}
      - run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
